CUDA_HOME=/leonardo/prod/opt/compilers/cuda/11.8/none
MPI_HOME=/leonardo/prod/spack/03/install/0.19/linux-rhel8-icelake/nvhpc-23.1/openmpi-4.1.4-6ek2oqarjw755glr5papxirjmamqwvgd
NCCL_HOME=/home/root/opt/nvhpc/Linux_x86_64/23.1/comm_libs/11.8/nccl

# CC=${MPI_HOME}/bin/mpicc
CC=nvcc
CFLAGS=-O3 -std=c++14
LIBS=-L$(MPI_HOME)/lib -L$(CUDA_HOME)/lib64 -L$(CUDA_HOME)/compact
INCL=-I$(MPI_HOME)/include -I$(CUDA_HOME)/include
LIBFLAGS=-lmpi -lcudart -lcuda
DBGFLAGS=-g -G

topology-finder: topology-finder.cu
	$(CC) $(CFLAGS) -o $@ $< $(INCL) $(LIBS) $(LIBFLAGS) -lstdc++ -lm -Wno-deprecated-gpu-targets $(DBGFLAGS)

clean:
	rm topology-finder

